name: Awoshe
description: Contemporary & luxurious African Designs Made for Men, Women, Kids and Homes.
version: 1.0.1+31
# update version and version code both
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  intl: ^0.16.0
  intl_translation: ^0.17.7
  sentry: any
  carousel_slider: ^1.3.0
  flutter_image_compress: ^0.6.3
  photo_view: ^0.9.0
  dots_indicator: ^0.0.4
  flutter_statusbarcolor: ^0.2.3
  equatable: ^0.2.3
  flutter_advanced_networkimage: ^0.6.0-alpha.1
  flare_flutter: any
  firebase_messaging: any
  firebase_core: ^0.4.0+5
  google_sign_in: any
  http: ^0.12.0+2
  cloud_firestore: ^0.13.0+1
  firebase_auth:
  firebase_storage:
  firebase_analytics:
  firebase_dynamic_links: 0.5.0+9
  firebase_remote_config:
  firebase_database: ^3.1.1
  flutter_facebook_login: ^3.0.0
  shared_preferences: ^0.5.3
  flutter_sticky_header: any
  webview_flutter: ^0.3.6
  flutter_inappwebview: ^2.1.0+1
  flushbar: ^1.4.0
  fluro: ^1.4.0
  image_picker: any
  flutter_svg: ^0.17.1 #^0.14.2
  flutter_bloc: ^0.21.0
  url_launcher: ^5.1.2
  rxdart: any
  flutter_staggered_grid_view: ^0.2.7
  json_annotation:
  cached_network_image: ^2.0.0-rc.1
  flutter_local_notifications: ^0.7.0
  collection: ^1.14.11
  built_value: ^6.3.0
  http_auth: ^0.2.5
  share: ^0.6.0+1
  flutter_webview_plugin: ^0.3.0+2
  package_info: any
  timeago: ^2.0.16
  image_cropper: ^1.1.0
  provider: ^3.0.0+1
  path: ^1.6.4
  sqflite: ^1.1.7+1
  mobx: ^0.4.0+1
  flutter_mobx: ^0.3.6
  flutter_masked_text: ^0.8.0
  shimmer: ^1.0.1
  basic_utils: ^2.2.4
  flutter_rating: ^0.0.2
  flutter_datetime_picker: ^1.2.8
  sliding_up_panel: ^0.3.6
  stripe_sdk: ^2.4.2
  flutter_cache_manager: ^1.1.3
  fa_stepper:
    git:
      url: git://github.com/sc4v3ng3r/fa_stepper.git
      ref: 61b996954b0b664a7471fb2db2e767730feaa26f
  flutter_paystack:
  video_player: ^0.10.6
  file_picker: ^1.4.3+2
  flutter_circle_color_picker: ^0.1.1
  #flutter_video_compress: ^0.3.7+8


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  json_serializable: any
  mobx_codegen: ^0.4.0+1
#dependency_overrides:
#  analyzer:

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/svg/Icons/
    - assets/svg/sustainable/
    - assets/Awoshe.flr
    - assets/category_size.json
    - assets/svg/Icons/care_icons/
  fonts:
    - family: Muli
      fonts:
        - asset: fonts/Muli.ttf
        - asset: fonts/Muli-SemiBold.ttf
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Regular.ttf
    - family: PlayfairDisplay
      fonts:
        - asset: fonts/PlayfairDisplay-Bold.otf
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf
    - family: newtabicons
      fonts:
        - asset: fonts/newtabicons.ttf

